# Generated by Django 5.0.4 on 2024-04-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_username", models.CharField(max_length=255)),
                ("level", models.IntegerField(default=0)),
                ("expirience", models.IntegerField(default=0)),
                ("right_answer", models.IntegerField()),
            ],
        ),
    ]
